### ISSUE TITLE
max memory size is never calculated unless percentage is used

### ISSUE THREAD

**Issue by cyberkov** [saz/puppet-memcached#100]
Hi!

When assigning a variable like max_memory = `2G`, it is converted to an integer, in this case `2`.

https://github.com/saz/puppet-memcached/blob/e517b447830398983007d17ea78d146f41e144e9/lib/puppet/functions/memcached/max_memory.rb#L11

Best wishes
Hannes

**Comment by saz** [comment]
Memcached expects max memory usage as MB.
I'm happy if you're sending in a pull request to make this conversion possible.
