### ISSUE TITLE
No changelog available

### ISSUE THREAD

**Issue by fatbasstard** [saz/puppet-memcached#102]
We're currently using 3.0.2 of this module, and we'd like to update it to a newer version.
The lack of a changelog makes this process more complex than needed.

Can you add a Changelog to this project? If possible with the historic data

**Comment by saz** [comment]
I've started a changelog now, but I'm sorry, I won't add historic data, as this takes too much time.

But to still help you a little bit: there shouldn't be a backwards incompatible change. Most commits are fixing testing issues or making use of Puppet data types.

As long as you're running Puppet 4.9 or newer, your upgrade should be no problem.
