### ISSUE TITLE
allow create multiple instance

### ISSUE THREAD

**Issue by Elbandi** [saz/puppet-memcached#106]
We run multiple memcached daemon in one node. we want to create it with this module, but cannot.

    class { 'memcached':
        listen_ip => "0.0.0.0",
        tcp_port => 11211,
        udp_port => 0,
        max_connections => 30000,
        max_memory => 1024,
        pidfile => "/var/run/memcached/main.pid",
    }
    class { 'memcached':
        listen_ip => "0.0.0.0",
        tcp_port => 11212,
        udp_port => 0,
        max_connections => 8192,
        max_memory => 128,
        pidfile => "/var/run/memcached/session.pid",
    }

**Comment by saz** [comment]
I've just merged a PR adding support for multiple instances. Please give the current master a try (this is only working on distributions using systemd)
