### ISSUE TITLE
Passing an array to memcached::listen doesn't work

### ISSUE THREAD

**Issue by kajinamit** [saz/puppet-memcached#133]
Currently the listen parameter (and the listen_ip parameter) is always converted to an array.

https://github.com/saz/puppet-memcached/blob/ca0d45e8599b838ddc379610ea12993e39959c14/manifests/init.pp#L74
https://github.com/saz/puppet-memcached/blob/ca0d45e8599b838ddc379610ea12993e39959c14/manifests/init.pp#L78

But we should not do this if the parameter has always an array.
Otherwise the real_listen variable becomes an Array of an Array which can't be handled by logics in erb templates properly.

**Comment by saz** [comment]
Please tell me the puppet version you're using and on which OS (distro) this is happening.
I've added some tests and they're running fine (puppet 6 and 7 RedHat and Debian based distros)

**Comment by kajinamit** [comment]
Sorry this was just my misunderstanding. I tested the same with Puppet 7.8.0 and Puppet-memcached 6.0.1 but it worked correctly.
