### ISSUE TITLE
Make release at puppet forge compatible with Puppet 8

### ISSUE THREAD

**Issue by siebrand** [saz/puppet-memcached#154]
Currently 8.2.0 fails:

  templates/memcached_sysconfig.erb, line: 57: Undefined variable 'osfamily';

**Comment by tmanninger** [comment]
Is already fixed:
https://github.com/saz/puppet-memcached/commit/3072cc22db8be118e2a2745b668358abb01c45b8

**Comment by siebrand** [comment]
Thanks for that, @tmanninger . I hadn't noticed. I took the module from puppet forge ([8.2.0](https://forge.puppet.com/modules/saz/memcached)), and that apparently hasn't been updated yet. I'll reword the issue.

**Comment by saz** [comment]
I'll wait for #142 and make a new release after merging it.

**Comment by saz** [comment]
8.3.0 has been released to the forge
