### ISSUE TITLE
Default pidfile on Ubuntu misplaced

### ISSUE THREAD

**Issue by toggetit** [saz/puppet-memcached#159]
Hello!
I found that default pidfile location is /var/run/memcached.pid, but there is some issues with it on Ubuntu:
```
root@ost-m03-v:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
```
1. Service cannot create PID file in this location with default 'nobody' (Ubuntu) user because of default permissions for /var/run (/run) is 644
```
root@ost-m03-v:~# systemctl status memcached.service 
● memcached.service - memcached daemon
     Loaded: loaded (/lib/systemd/system/memcached.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2024-04-10 15:19:32 MSK; 58s ago
       Docs: man:memcached(1)
   Main PID: 1623154 (memcached)
      Tasks: 12 (limit: 9388)
     Memory: 10.4M
        CPU: 112ms
     CGroup: /system.slice/memcached.service
             └─1623154 /usr/bin/memcached -P /var/run/memcached.pid -m 793 -l X.X.X.X -p 11211 -U 0 -u nobody -c 8192 -t 6
Apr 10 15:19:32 ost-m03-v systemd[1]: Started memcached daemon.
Apr 10 15:19:32 ost-m03-v systemd-memcached-wrapper[1623154]: Could not open the pid file /var/run/memcached.pid.tmp for writing: Permission denied

root@ost-m03-v:~# ls -lh / | grep run
drwxr-xr-x  47 root root 1.3K Apr 10 15:35 run
```
2. But official memcached deb-package from Ubuntu repos creates special PID directory /var/run/memcached with permissions for internal (built-in in package) service user (memcache). Please see https://github.com/saz/puppet-memcached/issues/105
```
root@ost-m03-v:~# ls -lh /run/ | grep memcache
drwxr-xr-x  2 memcache  memcache    60 Apr 10 15:35 memcached
```
So for correct work on Ubuntu (minimum) we need to:
1. Change default pidfile to /var/run/memcached/memcached.pid
2. Change run as user from nobody to memcache

**Comment by saz** [comment]
Fixed with the merge of #160
