### ISSUE TITLE
memcached.log : "Could not open the pid file /var/run/memcached.pid for writing: Permission denied"

### ISSUE THREAD

**Issue by grafana-dee** [saz/puppet-memcached#27]
Is anyone else seeing this?

I'm running Memcached on Ubuntu server and the /etc/init.d/memcached script creates the PID file using root:root as owner.

In the memcached.conf file generated by this puppet module, a PID file is specified and an attempt to create the PID file fails because the default user 'nobody' on Ubuntu cannot create the file (given that the init.d script already created it with owner root).

If I comment out line seven referring to the PID file in https://github.com/saz/puppet-memcached/blob/master/templates/memcached.conf.erb

Then no errors are generated and memcached daemonizes cleanly and without warnings.

If I do not comment out line seven then the log file ends up filling with statements like this every time the process status is changed:

```
WARNING: The pid file contained the following (running) pid: 20738
Could not open the pid file /var/run/memcached.pid for writing: Permission denied
WARNING: The pid file contained the following (running) pid: 22334
Could not open the pid file /var/run/memcached.pid for writing: Permission denied
WARNING: The pid file contained the following (running) pid: 24377
Could not open the pid file /var/run/memcached.pid for writing: Permission denied
WARNING: The pid file contained the following (running) pid: 2541
Could not open the pid file /var/run/memcached.pid for writing: Permission denied
WARNING: The pid file contained the following (running) pid: 6287
Could not open the pid file /var/run/memcached.pid for writing: Permission denied
```

If this is just me, I'll comment it out locally. If this affects everyone using this module, on Red Hat as well as Ubuntu, then maybe line 7 should be removed from the config.

**Comment by harem234** [comment]
just create a directory in
`sudo mkdir /var/run/memcached`

change the permissions of the directory
`sudo chown memcached:memcached memcached`
