### ISSUE TITLE
Set additional memcached options

### ISSUE THREAD

**Issue by cdsmmeyer** [saz/puppet-memcached#71]
Here is a process that was started. 

492      23453     1  0 16:08 ?        00:00:00 memcached -d -p 11211 -u memcached -m 512 -c 2048 -P /var/run/memcached/memcached.pid -t 1

How can we change or eliminate the -t 1 option and also how can we add other options to run?  We use the -I option, which specifies the maximum size permitted for storing an object within the memcached instance. The size supports a unit postfix (k for kilobytes, m for megabytes). For example, to increase the maximum supported object size to 32MB:

https://docs.oracle.com/cd/E17952_01/refman-5.0-en/ha-memcached-using.html

Please advise.  Thanks

**Comment by saz** [comment]
The value for ```-t``` is passed in through parameter ```processorcount```. It can be changed, but not completely removed. If you think, this would be required, it's easy to change it in such way.

The value for ```-I``` might be changed with the ```item_size``` parameter.

Please let me know, if you've got some ideas on improving the current documentation to make this module easier to use.
