### ISSUE TITLE
CentOS 7 unix_socket does nothing

### ISSUE THREAD

**Issue by unixpro** [saz/puppet-memcached#78]
Checked generated /etc/sysconfig/memcached and OPTIONS still looks like this:
OPTIONS="-l 0.0.0.0 -U 11211 -t 4 >> /var/log/memcached.log 2>&1"

Other options like memory size working correct and is there.

Looked at module source and templates/memcached_sysconfig.erb does not even contain/use the unix_socket variable.

**Comment by saz** [comment]
Fixed in the current master
