### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by cristianbalan-mf** [saz/puppet-memcached#87]
Hi, how come there is no changelog in Puppet Forge and here at all?
I'm using the 2.8.1 so I want to find out what happened in the three updates released afterwards.

**Comment by byblakout** [comment]
+1
Changelog would be appreciated!

**Comment by kpankonen** [comment]
https://github.com/saz/puppet-memcached/compare/v2.8.1...v3.0.1

**Comment by saz** [comment]
If you point me to an easy way of maintaining a changelog, I'll be more than happy to add one.

**Comment by saz** [comment]
This will be resolved, when #91 is resolved.
