### ISSUE TITLE
retun_types only work Puppet 4.8 later 

### ISSUE THREAD

**Issue by kkarthee** [saz/puppet-memcached#94]
https://github.com/saz/puppet-memcached/blob/master/lib/puppet/functions/memcached/max_memory.rb#L5

https://tickets.puppetlabs.com/browse/PUP-7831

https://puppet.com/docs/puppet/4.8/lang_write_functions_in_puppet.html#return-types

Note: Return types only work with Puppet 4.8 and later. In earlier versions of Puppet, they cause an evaluation error.

**Comment by saz** [comment]
Should be fixed in the current master version
